### ISSUE TITLE
Solar mode is killing FLASH

### ISSUE THREAD

**Issue by DM5TU** [lora-aprs/LoRa_APRS_iGate#69]
I am running the iGate battery powered and buffered by a solar panel. 

If the battery runs empty bcu the solar energy is not enough to reload the battery, the iGate reports the ERROR showed on the picture. 

I was able to reproduce that failure repeatedly. 

Maybe it is a bug in software. 

![image](https://user-images.githubusercontent.com/64897048/109156304-f7a8a800-7770-11eb-82be-122b8eb411ff.jpeg)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - PlatformIO Version: 
 - Firmware Version: 

**Board name:**
- 

**Additional context**
73 de sTef DM5TU

**Comment by DM5TU** [comment]
@peterus 
I was able to connect the board to the PC tonight.
I found some issues in the VSC.
Maybe its helpful somehow.

I needed to upload the sketch again.

Now its running again.
Let me know if you like to do some testing .

73 de sTef DM5TU
![iGate Issues ](https://user-images.githubusercontent.com/64897048/109215056-eb453f00-77b2-11eb-9fca-5b630acf1d3a.JPG)

**Comment by peterus** [comment]
thanks for showing me this. unfortunately this will be very tricky to solve and i think this will be an issue with the chip. the settings are stored in the flash which could get corrupted because of the to low voltage.
Is it possible to add some HW protection which is outputing the 5v or nothing?

the issues which are shown in the picture are not really issues with the firmware. VSC is just trying to get some stuff together but doesn't have all information from platformio. if the compile is okay, it will work ;)

**Comment by peterus** [comment]
@DM5TU is this issue still existing with the latest firmware?
